"""Refactor models for energy dashboard features

Revision ID: 5e2d3bd5e9c1
Revises: b5fd4bc37272
Create Date: 2025-09-07 05:30:30.387791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2d3bd5e9c1'
down_revision: Union[str, Sequence[str], None] = 'b5fd4bc37272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_cost_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batteries_id'), 'batteries', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reimbursement_rate_eur_per_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_table('solar_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_cost_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_power_wp', sa.Integer(), nullable=False),
    sa.Column('expected_annual_yield_kwh', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_panels_id'), 'solar_panels', ['id'], unique=False)
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')

    op.rename_table('monthly_metrics', 'monthly_journal')

    op.create_table('car_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('total_charged_kwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['monthly_journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_journal_entries_id'), 'car_journal_entries', ['id'], unique=False)

    with op.batch_alter_table('monthly_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('grid_consumption_low_kwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grid_consumption_high_kwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grid_feed_in_low_kwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grid_feed_in_high_kwh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consumption_price_low_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True))
        batch_op.add_column(sa.Column('consumption_price_high_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True))
        batch_op.add_column(sa.Column('feed_in_tariff_low_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True))
        batch_op.add_column(sa.Column('feed_in_tariff_high_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True))
        batch_op.add_column(sa.Column('solar_production_kwh', sa.Float(), nullable=True))
        batch_op.alter_column('monthly_prepayment_eur', existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
        batch_op.alter_column('battery_charge_kwh', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('battery_discharge_kwh', existing_type=sa.FLOAT(), nullable=True)
        batch_op.drop_column('export_total_kwh')
        batch_op.drop_column('consumption_ev_kwh')
        batch_op.drop_column('import_high_kwh')
        batch_op.drop_column('import_low_kwh')
        batch_op.drop_column('production_total_kwh')
        batch_op.drop_column('period_start')
        batch_op.drop_column('account_name')


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('period_start', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('production_total_kwh', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_low_kwh', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_high_kwh', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('consumption_ev_kwh', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('export_total_kwh', sa.FLOAT(), nullable=True))
        batch_op.alter_column('monthly_prepayment_eur', existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
        batch_op.alter_column('battery_charge_kwh', existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column('battery_discharge_kwh', existing_type=sa.FLOAT(), nullable=False)
        batch_op.drop_column('solar_production_kwh')
        batch_op.drop_column('feed_in_tariff_high_eur_kwh')
        batch_op.drop_column('feed_in_tariff_low_eur_kwh')
        batch_op.drop_column('consumption_price_high_eur_kwh')
        batch_op.drop_column('consumption_price_low_eur_kwh')
        batch_op.drop_column('grid_feed_in_high_kwh')
        batch_op.drop_column('grid_feed_in_low_kwh')
        batch_op.drop_column('grid_consumption_high_kwh')
        batch_op.drop_column('grid_consumption_low_kwh')
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    op.rename_table('monthly_journal', 'monthly_metrics')

    op.create_table('investments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('installation_date', sa.DATE(), nullable=False),
    sa.Column('total_cost_eur', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_power_wp', sa.INTEGER(), nullable=False),
    sa.Column('estimated_annual_production_kwh', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.drop_index(op.f('ix_car_journal_entries_id'), table_name='car_journal_entries')
    op.drop_table('car_journal_entries')
    op.drop_index(op.f('ix_solar_panels_id'), table_name='solar_panels')
    op.drop_table('solar_panels')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_batteries_id'), table_name='batteries')
    op.drop_table('batteries')
    # ### end Alembic commands ###
