version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://jj:jjpass@db:5432/joulejournal
      SECRET_KEY: super-secret-change-me
      ACCESS_TOKEN_EXPIRES_MINUTES: 1440
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: joulejournal
      POSTGRES_USER: jj
      POSTGRES_PASSWORD: jjpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}
