"""Create initial tables

Revision ID: 1a2b3c4d5e6f
Revises:
Create Date: 2025-09-06 12:38:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_energy',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('low_tariff_eur_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('high_tariff_eur_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('feedin_rate_eur_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ev_kwh', sa.Float(), nullable=True),
    sa.Column('auto_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pv_backfeed_kwh', sa.Float(), nullable=True),
    sa.Column('pv_production_kwh', sa.Float(), nullable=True),
    sa.Column('house_low_kwh', sa.Float(), nullable=True),
    sa.Column('house_high_kwh', sa.Float(), nullable=True),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=True),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_without_battery_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_without_battery_kwh', sa.Float(), nullable=True),
    sa.Column('advance_payment_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('settlement_to_own_account_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('billed_kwh', sa.Float(), nullable=True),
    sa.Column('energy_unit_price_eur', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='_year_month_uc')
    )
    op.create_table('solar_investment_option',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('panels', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.String(), nullable=True),
    sa.Column('total_power_wp', sa.Integer(), nullable=True),
    sa.Column('annual_production_kwh', sa.Float(), nullable=True),
    sa.Column('inverter', sa.String(), nullable=True),
    sa.Column('assumed_energy_price_eur_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('total_cost_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_monthly_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('pv_production_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='_solar_ref_year_month_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_monthly_reference')
    op.drop_table('solar_investment_option')
    op.drop_table('monthly_energy')
    # ### end Alembic commands ###
