"""Add battery and solar panel tables

Revision ID: 656b4301ba15
Revises: e9b403db6e1e
Create Date: 2025-09-12 20:12:14.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656b4301ba15'
down_revision: Union[str, None] = 'e9b403db6e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost_eur', sa.Float(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batteries_id'), 'batteries', ['id'], unique=False)
    op.create_index(op.f('ix_batteries_name'), 'batteries', ['name'], unique=False)
    op.create_table('solar_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost_eur', sa.Float(), nullable=False),
    sa.Column('power_capacity_kwp', sa.Float(), nullable=False),
    sa.Column('expected_yield_kwh_per_kwp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_panels_id'), 'solar_panels', ['id'], unique=False)
    op.create_index(op.f('ix_solar_panels_name'), 'solar_panels', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_panels_name'), table_name='solar_panels')
    op.drop_index(op.f('ix_solar_panels_id'), table_name='solar_panels')
    op.drop_table('solar_panels')
    op.drop_index(op.f('ix_batteries_name'), table_name='batteries')
    op.drop_index(op.f('ix_batteries_id'), table_name='batteries')
    op.drop_table('batteries')
    # ### end Alembic commands ###
