"""Add Tariff model

Revision ID: aada757623b7
Revises: 5e2d3bd5e9c1
Create Date: 2025-09-07 09:58:20.257291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aada757623b7'
down_revision: Union[str, Sequence[str], None] = '5e2d3bd5e9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('purchase_low_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('purchase_high_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('sale_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_roi_rate_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    op.alter_column('batteries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_journal')
    op.create_index(op.f('ix_monthly_journal_id'), 'monthly_journal', ['id'], unique=False)
    op.alter_column('solar_panels', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solar_panels', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_monthly_journal_id'), table_name='monthly_journal')
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_journal', ['id'], unique=False)
    op.alter_column('batteries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
