"""Add Tariff model

Revision ID: aada757623b7
Revises: 5e2d3bd5e9c1
Create Date: 2025-09-07 09:58:20.257291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aada757623b7'
down_revision: Union[str, Sequence[str], None] = '5e2d3bd5e9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)

    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_journal')
    op.create_index(op.f('ix_monthly_journal_id'), 'monthly_journal', ['id'], unique=False)

    with op.batch_alter_table('solar_panels', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_panels', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

    op.drop_index(op.f('ix_monthly_journal_id'), table_name='monthly_journal')
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_journal', ['id'], unique=False)

    with op.batch_alter_table('batteries', schema=None) as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###
