"""Initial migration

Revision ID: b5fd4bc37272
Revises:
Create Date: 2025-09-06 07:49:59.933163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fd4bc37272'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('total_cost_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_power_wp', sa.Integer(), nullable=False),
    sa.Column('estimated_annual_production_kwh', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_table('monthly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('production_total_kwh', sa.Float(), nullable=True),
    sa.Column('import_low_kwh', sa.Float(), nullable=True),
    sa.Column('import_high_kwh', sa.Float(), nullable=True),
    sa.Column('export_total_kwh', sa.Float(), nullable=True),
    sa.Column('consumption_ev_kwh', sa.Float(), nullable=True),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=True),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('monthly_prepayment_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start')
    )
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_metrics', ['id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('purchase_low_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('purchase_high_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('sale_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fixed_roi_rate_eur_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_metrics')
    op.drop_table('monthly_metrics')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
