"""Initial migration creating investment, tariff, and metric tables

Revision ID: d9a5b3f7d1e9
Revises:
Create Date: 2025-09-05 23:11:30.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a5b3f7d1e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=False),
    sa.Column('total_investment_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_wp', sa.Integer(), nullable=False),
    sa.Column('estimated_annual_production_kwh', sa.Integer(), nullable=True),
    sa.Column('inverter_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)

    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('purchase_rate_low', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('purchase_rate_high', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('feed_in_rate', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fixed_roi_rate', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)

    op.create_table('monthly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('total_generated_kwh', sa.Float(), nullable=True),
    sa.Column('import_low_rate_kwh', sa.Float(), nullable=True),
    sa.Column('import_high_rate_kwh', sa.Float(), nullable=True),
    sa.Column('total_feed_in_kwh', sa.Float(), nullable=True),
    sa.Column('ev_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=True),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('prepayment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period')
    )
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_metrics')
    op.drop_table('monthly_metrics')
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    # ### end Alembic commands ###
