"""Add journal car and entity tables

Revision ID: e9b403db6e1e
Revises: 418ae91b3611
Create Date: 2025-09-12 12:31:17.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b403db6e1e'
down_revision: Union[str, None] = '418ae91b3611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reimbursement_rate_eur_per_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_name'), 'cars', ['name'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_table('monthly_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('grid_consumption_low_kwh', sa.Float(), nullable=True),
    sa.Column('grid_consumption_high_kwh', sa.Float(), nullable=True),
    sa.Column('grid_feed_in_low_kwh', sa.Float(), nullable=True),
    sa.Column('grid_feed_in_high_kwh', sa.Float(), nullable=True),
    sa.Column('consumption_price_low_eur_kwh', sa.Float(), nullable=True),
    sa.Column('consumption_price_high_eur_kwh', sa.Float(), nullable=True),
    sa.Column('feed_in_tariff_low_eur_kwh', sa.Float(), nullable=True),
    sa.Column('feed_in_tariff_high_eur_kwh', sa.Float(), nullable=True),
    sa.Column('solar_production_kwh', sa.Float(), nullable=True),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=True),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=True),
    sa.Column('monthly_prepayment_eur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_journal_id'), 'monthly_journal', ['id'], unique=False)
    op.create_table('car_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_charged_kwh', sa.Float(), nullable=False),
    sa.Column('monthly_journal_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['monthly_journal_id'], ['monthly_journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_journal_entries_id'), 'car_journal_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_journal_entries_id'), table_name='car_journal_entries')
    op.drop_table('car_journal_entries')
    op.drop_index(op.f('ix_monthly_journal_id'), table_name='monthly_journal')
    op.drop_table('monthly_journal')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_cars_name'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
